# Generated by Django 4.1.4 on 2022-12-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaxter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
