# Generated by Django 4.1.4 on 2022-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaxter', '0002_rename_menuitems_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('American', 'American'), ('Chinese', 'Chinese'), ('Greek', 'Greek'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Mexican', 'Mexican'), ('Thai', 'Thai')], max_length=50),
        ),
    ]
