# Generated by Django 4.1.4 on 2022-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaxter', '0005_alter_menuitem_restaurant_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closes',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opens',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
